params:
  cuda_devices: [ 0,2 ]
  docker_env:
    HTTP_PROXY: localhost:12312
    HTTPS_PROXY: localhost:12312
    NO_PROXY: localhost:12312

optional_plugin_components:
  cuda_device_monitor:
    template: openfl.plugins.processing_units_monitor.pynvml_monitor.PynvmlCUDADeviceMonitor
    settings: [ ]

shard_descriptor:
  template: kvasir_shard_descriptor.KvasirShardDescriptor
  params:
    data_folder: kvasir_data
    rank_worldsize: 1,10
    enforce_image_hw: '300,400'
